let fakeCelebrities = [{
    "id": 1,
    "firstName": "Edie",
    "lastName": "Faull",
    "age": 53,
    "gender": "Male",
    "image": "http://dummyimage.com/169x238.png/ff4444/ffffff",
    "price": 84
  }, {
    "id": 2,
    "firstName": "Ethe",
    "lastName": "Balasin",
    "age": 54,
    "gender": "Male",
    "image": "http://dummyimage.com/241x151.bmp/ff4444/ffffff",
    "price": 76
  }, {
    "id": 3,
    "firstName": "Mortie",
    "lastName": "Colliar",
    "age": 57,
    "gender": "Male",
    "image": "http://dummyimage.com/177x200.jpg/ff4444/ffffff",
    "price": 193
  }, {
    "id": 4,
    "firstName": "Kris",
    "lastName": "O'Brien",
    "age": 46,
    "gender": "Male",
    "image": "http://dummyimage.com/116x181.png/cc0000/ffffff",
    "price": 27
  }, {
    "id": 5,
    "firstName": "Reed",
    "lastName": "Waddy",
    "age": 32,
    "gender": "Male",
    "image": "http://dummyimage.com/125x123.bmp/5fa2dd/ffffff",
    "price": 53
  }, {
    "id": 6,
    "firstName": "Noemi",
    "lastName": "Brannigan",
    "age": 20,
    "gender": "Female",
    "image": "http://dummyimage.com/209x119.jpg/dddddd/000000",
    "price": 141
  }, {
    "id": 7,
    "firstName": "Perrine",
    "lastName": "Torel",
    "age": 42,
    "gender": "Female",
    "image": "http://dummyimage.com/145x164.bmp/cc0000/ffffff",
    "price": 42
  }, {
    "id": 8,
    "firstName": "Kaitlin",
    "lastName": "Bartelli",
    "age": 53,
    "gender": "Female",
    "image": "http://dummyimage.com/224x128.png/5fa2dd/ffffff",
    "price": 219
  }, {
    "id": 9,
    "firstName": "Virginie",
    "lastName": "Wedmore.",
    "age": 62,
    "gender": "Female",
    "image": "http://dummyimage.com/238x237.jpg/dddddd/000000",
    "price": 289
  }, {
    "id": 10,
    "firstName": "Bronnie",
    "lastName": "Stetson",
    "age": 64,
    "gender": "Male",
    "image": "http://dummyimage.com/240x149.jpg/cc0000/ffffff",
    "price": 277
  }, {
    "id": 11,
    "firstName": "Douglas",
    "lastName": "Carles",
    "age": 40,
    "gender": "Male",
    "image": "http://dummyimage.com/240x188.jpg/dddddd/000000",
    "price": 231
  }, {
    "id": 12,
    "firstName": "Lacey",
    "lastName": "Fouch",
    "age": 52,
    "gender": "Female",
    "image": "http://dummyimage.com/210x224.jpg/cc0000/ffffff",
    "price": 76
  }, {
    "id": 13,
    "firstName": "Phyllida",
    "lastName": "Kybbye",
    "age": 76,
    "gender": "Female",
    "image": "http://dummyimage.com/195x150.bmp/cc0000/ffffff",
    "price": 214
  }, {
    "id": 14,
    "firstName": "Edvard",
    "lastName": "Scase",
    "age": 32,
    "gender": "Male",
    "image": "http://dummyimage.com/208x220.bmp/cc0000/ffffff",
    "price": 232
  }, {
    "id": 15,
    "firstName": "Jacquelynn",
    "lastName": "Emeny",
    "age": 29,
    "gender": "Female",
    "image": "http://dummyimage.com/162x104.bmp/cc0000/ffffff",
    "price": 46
  }, {
    "id": 16,
    "firstName": "Selma",
    "lastName": "Goodbody",
    "age": 21,
    "gender": "Female",
    "image": "http://dummyimage.com/100x104.jpg/cc0000/ffffff",
    "price": 128
  }, {
    "id": 17,
    "firstName": "Bartholemy",
    "lastName": "Towne",
    "age": 58,
    "gender": "Male",
    "image": "http://dummyimage.com/214x241.png/cc0000/ffffff",
    "price": 87
  }, {
    "id": 18,
    "firstName": "Sigvard",
    "lastName": "Saxton",
    "age": 30,
    "gender": "Male",
    "image": "http://dummyimage.com/103x128.jpg/ff4444/ffffff",
    "price": 186
  }, {
    "id": 19,
    "firstName": "Candra",
    "lastName": "Drysdale",
    "age": 63,
    "gender": "Female",
    "image": "http://dummyimage.com/202x100.bmp/ff4444/ffffff",
    "price": 251
  }, {
    "id": 20,
    "firstName": "Maire",
    "lastName": "Shinefield",
    "age": 72,
    "gender": "Female",
    "image": "http://dummyimage.com/199x217.png/5fa2dd/ffffff",
    "price": 221
  }, {
    "id": 21,
    "firstName": "Jessalin",
    "lastName": "Trickey",
    "age": 26,
    "gender": "Female",
    "image": "http://dummyimage.com/219x241.jpg/ff4444/ffffff",
    "price": 53
  }, {
    "id": 22,
    "firstName": "Florette",
    "lastName": "Dymocke",
    "age": 39,
    "gender": "Female",
    "image": "http://dummyimage.com/126x187.bmp/ff4444/ffffff",
    "price": 264
  }, {
    "id": 23,
    "firstName": "Nealon",
    "lastName": "Delle",
    "age": 80,
    "gender": "Male",
    "image": "http://dummyimage.com/188x185.bmp/5fa2dd/ffffff",
    "price": 233
  }, {
    "id": 24,
    "firstName": "Margaretha",
    "lastName": "Sturney",
    "age": 66,
    "gender": "Female",
    "image": "http://dummyimage.com/109x126.bmp/ff4444/ffffff",
    "price": 208
  }, {
    "id": 25,
    "firstName": "Anatole",
    "lastName": "Stellino",
    "age": 45,
    "gender": "Male",
    "image": "http://dummyimage.com/105x247.png/cc0000/ffffff",
    "price": 27
  }, {
    "id": 26,
    "firstName": "Kaja",
    "lastName": "Gilloran",
    "age": 78,
    "gender": "Female",
    "image": "http://dummyimage.com/199x155.png/ff4444/ffffff",
    "price": 217
  }, {
    "id": 27,
    "firstName": "Phyllida",
    "lastName": "Keyzman",
    "age": 52,
    "gender": "Female",
    "image": "http://dummyimage.com/154x151.jpg/dddddd/000000",
    "price": 203
  }, {
    "id": 28,
    "firstName": "Tybi",
    "lastName": "Somes",
    "age": 43,
    "gender": "Female",
    "image": "http://dummyimage.com/118x232.jpg/ff4444/ffffff",
    "price": 73
  }, {
    "id": 29,
    "firstName": "Filmer",
    "lastName": "Trevino",
    "age": 55,
    "gender": "Male",
    "image": "http://dummyimage.com/202x145.jpg/5fa2dd/ffffff",
    "price": 260
  }, {
    "id": 30,
    "firstName": "Edeline",
    "lastName": "Dugood",
    "age": 71,
    "gender": "Female",
    "image": "http://dummyimage.com/143x140.png/cc0000/ffffff",
    "price": 36
  }, {
    "id": 31,
    "firstName": "Kerr",
    "lastName": "Bernadzki",
    "age": 77,
    "gender": "Male",
    "image": "http://dummyimage.com/240x128.bmp/dddddd/000000",
    "price": 281
  }, {
    "id": 32,
    "firstName": "Hew",
    "lastName": "Zorzoni",
    "age": 53,
    "gender": "Male",
    "image": "http://dummyimage.com/209x125.png/5fa2dd/ffffff",
    "price": 196
  }, {
    "id": 33,
    "firstName": "Thibaut",
    "lastName": "Creek",
    "age": 48,
    "gender": "Male",
    "image": "http://dummyimage.com/115x221.png/cc0000/ffffff",
    "price": 45
  }, {
    "id": 34,
    "firstName": "Tiena",
    "lastName": "Baskwell",
    "age": 71,
    "gender": "Female",
    "image": "http://dummyimage.com/174x190.png/dddddd/000000",
    "price": 206
  }, {
    "id": 35,
    "firstName": "Silvio",
    "lastName": "McLucky",
    "age": 78,
    "gender": "Male",
    "image": "http://dummyimage.com/250x199.jpg/dddddd/000000",
    "price": 90
  }, {
    "id": 36,
    "firstName": "Neron",
    "lastName": "Yerborn",
    "age": 41,
    "gender": "Male",
    "image": "http://dummyimage.com/233x215.jpg/dddddd/000000",
    "price": 33
  }, {
    "id": 37,
    "firstName": "Wallie",
    "lastName": "Corde",
    "age": 71,
    "gender": "Male",
    "image": "http://dummyimage.com/142x114.jpg/dddddd/000000",
    "price": 117
  }, {
    "id": 38,
    "firstName": "Marnia",
    "lastName": "Kibbel",
    "age": 71,
    "gender": "Female",
    "image": "http://dummyimage.com/162x213.bmp/cc0000/ffffff",
    "price": 219
  }, {
    "id": 39,
    "firstName": "Lynett",
    "lastName": "Tripet",
    "age": 32,
    "gender": "Female",
    "image": "http://dummyimage.com/155x186.bmp/cc0000/ffffff",
    "price": 242
  }, {
    "id": 40,
    "firstName": "Gordon",
    "lastName": "Priver",
    "age": 60,
    "gender": "Male",
    "image": "http://dummyimage.com/103x183.png/5fa2dd/ffffff",
    "price": 96
  }, {
    "id": 41,
    "firstName": "Roth",
    "lastName": "Brighouse",
    "age": 49,
    "gender": "Male",
    "image": "http://dummyimage.com/109x137.bmp/cc0000/ffffff",
    "price": 40
  }, {
    "id": 42,
    "firstName": "Maggie",
    "lastName": "McMurraya",
    "age": 80,
    "gender": "Female",
    "image": "http://dummyimage.com/153x218.jpg/ff4444/ffffff",
    "price": 209
  }, {
    "id": 43,
    "firstName": "Kelly",
    "lastName": "Selvey",
    "age": 38,
    "gender": "Male",
    "image": "http://dummyimage.com/139x152.png/5fa2dd/ffffff",
    "price": 225
  }, {
    "id": 44,
    "firstName": "Griswold",
    "lastName": "Featherstone",
    "age": 44,
    "gender": "Male",
    "image": "http://dummyimage.com/167x201.jpg/5fa2dd/ffffff",
    "price": 78
  }, {
    "id": 45,
    "firstName": "Andi",
    "lastName": "Cockshutt",
    "age": 70,
    "gender": "Female",
    "image": "http://dummyimage.com/130x236.png/5fa2dd/ffffff",
    "price": 25
  }, {
    "id": 46,
    "firstName": "Ashlie",
    "lastName": "Brabender",
    "age": 76,
    "gender": "Female",
    "image": "http://dummyimage.com/122x199.bmp/cc0000/ffffff",
    "price": 114
  }, {
    "id": 47,
    "firstName": "Gene",
    "lastName": "McMyler",
    "age": 35,
    "gender": "Female",
    "image": "http://dummyimage.com/169x159.bmp/ff4444/ffffff",
    "price": 272
  }, {
    "id": 48,
    "firstName": "Rafael",
    "lastName": "MacKonochie",
    "age": 22,
    "gender": "Male",
    "image": "http://dummyimage.com/127x213.png/cc0000/ffffff",
    "price": 276
  }, {
    "id": 49,
    "firstName": "Maris",
    "lastName": "Ainsworth",
    "age": 39,
    "gender": "Female",
    "image": "http://dummyimage.com/198x142.bmp/dddddd/000000",
    "price": 194
  }, {
    "id": 50,
    "firstName": "Windham",
    "lastName": "Grills",
    "age": 70,
    "gender": "Male",
    "image": "http://dummyimage.com/246x179.png/5fa2dd/ffffff",
    "price": 269
  }]